name: lab_on_chip_monitor
description: Lab-on-Chip Medical Device Monitor

publish_to: 'none'
version: 1.2.6+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  fl_chart: ^0.68.0
  window_manager: ^0.3.8
  pdf: ^3.10.8
  printing: ^5.12.0
  path_provider: ^2.1.3   # sandbox-safe file paths on macOS
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

flutter_launcher_icons:
  macos:
    generate: true
    image_path: "assets/icon/icon.png"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
